# -*- coding: utf-8 -*-
"""modeloptimization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1idrXmeuYsmIRA1BDR9ts8ACkMu_d8hxK
"""

def bij_transform(prime, lower, upper):
  """Recieves a prime value in [-inf, inf] and returns value in [lower, upper]"""
  bij = 1 / (1 + torch.exp(-prime / upper))
  scale = upper - lower
  return scale * bij + lower

def bij_transform_inv(transf, lower, upper):
  """Inverse transformation - Recieves a value in [lower, upper] and returns value in [-inf, inf]"""
  return -torch.log(((upper - lower) / (transf - lower) - 1) ** upper)